version: '{build}'

clone_depth: 2

environment:
  SCOOP_HOME: c:\projects\scoop

install:
  - cd c:\projects
  - git clone -b v0.2.2 --depth 1 https://github.com/ScoopInstaller/Scoop.git
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser -RequiredVersion 4.10.1
  - ps: Install-Module BuildHelpers -Force -SkipPublisherCheck -Scope CurrentUser

build: off

test_script:
  - ps: Invoke-Pester -EnableExit
