version: '{build}'

clone_depth: 1

environment:
  SCOOP_HOME: c:\projects\scoop

install:
  - cd c:\projects
  - git clone --depth 1 https://github.com/lukesampson/scoop.git
  - cd %APPVEYOR_BUILD_FOLDER%
  - ps: Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser
  - ps: Install-Module BuildHelpers -Force -SkipPublisherCheck -Scope CurrentUser

build: off

test_script:
  - ps: Invoke-Pester -EnableExit
