name: Scoop Update

on:
  schedule:
    - cron:  '0 7,14,21 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    name: Check manifest updates
    runs-on: windows-latest
    outputs:
      apps: ${{ steps.checkver.outputs.apps }}
    steps:
      - name: Checkout self
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Checkout scoop
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: scoop
          repository: lukesampson/scoop
          persist-credentials: false

      - name: Run checkver
        id: checkver
        run: |
          .\scripts\check-update.ps1
          Get-Content $env:GITHUB_OUTPUT
        env:
          SCOOP_HOME: scoop

  pr:
    name: Create PRs for updated manifests
    runs-on: windows-latest
    needs: check
    strategy:
      matrix:
        app: "${{ fromJSON(needs.check.outputs.apps) }}"
    permissions:
      contents: write       # update the manifest file.
      pull-requests: write  # create pull requests.
    steps:
      - name: Checkout self
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true # required for git push.

      - name: Checkout scoop
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: scoop
          repository: lukesampson/scoop
          persist-credentials: false

      - name: Update manifest
        id: update-manifest
        if: ${{ matrix.app != '__NONE__' }}
        run: |
          .\scoop\bin\checkver.ps1 -Dir bucket -App $env:MATRIX_APP -Update
          $version = (gc "bucket\$env:MATRIX_APP.json" | ConvertFrom-Json).version
          "version=$version`n" | Out-File -NoNewline -Encoding utf8 -Append $env:GITHUB_OUTPUT
        env:
          MATRIX_APP: ${{ matrix.app }}

      - name: Exclude scoop directory
        run: |
          "/scoop/`n" | Out-File -NoNewline -Encoding utf8 -Append .git\info\exclude

      - name: Create Pull Request
        if: ${{ matrix.app != '__NONE__' }}
        run: |
          $branch = "manifest-update/$env:MATRIX_APP-$env:APP_VERSION"

          $existing = gh pr list --head $branch --state open --json number | ConvertFrom-Json
          if ($existing) {
            Write-Host "Pull request already exists for $branch. Skipping."
            exit 0
          }

          git config user.name "iquiw"
          git config user.email "238681+iquiw@users.noreply.github.com"

          git switch -C $branch
          git add .
          git commit -m "${env:MATRIX_APP}: Update to version to $env:APP_VERSION"

          git push -u --force origin $branch

          $homepage = (gc "bucket\$env:MATRIX_APP.json" | ConvertFrom-Json).homepage

          gh pr create `
              --title "${env:MATRIX_APP}: Update to version to $env:APP_VERSION" `
              --body "[$env:MATRIX_APP]($homepage) $env:APP_VERSION" `
              --label "version up" `
              --label "automated pr" `
              --assignee iquiw `
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MATRIX_APP: ${{ matrix.app }}
          APP_VERSION: ${{ steps.update-manifest.outputs.version }}
